### PR TITLE
[NUI] Make BindingMode as internal

### PR DESCRIPTION
**Pull request by elishateng**
1. Make BindingMode as internal

### CODE REVIEW

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AdunFang — APPROVED** [review]
It is OK.

**Review by zg2nets — APPROVED** [review]
good！

**Review by everLEEst — APPROVED** [review]
LGTM.

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Pull request merged**
