### PR TITLE
[XamlBuild]Fix issue of default param in constructor in EXaml(JIRA 2299)

### PR DESCRIPTION
**Pull request by AdunFang**

### CODE REVIEW

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by elishateng — APPROVED** [review]
LGTM

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by AchoWang — COMMENTED** [review]
Looks good to me.

**Pull request merged**
