### PR TITLE
[EXaml] Support Trigger in EXaml

### PR DESCRIPTION
**Pull request by AdunFang**
Support Trigger in EXaml
relate to https://github.com/Samsung/TizenFX/pull/3480

### CODE REVIEW

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Review by elishateng — APPROVED** [review]
LGTM

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zg2nets — APPROVED** [review]
LGTM

**Comment by dongsug-song** [comment]
I merge this, but I will release this after tizenfx patch has been released.
thank you.

**Pull request merged**
