### PR TITLE
[XamlBuild] Clear statis member when build examl.

### PR DESCRIPTION
**Pull request by AdunFang**
Fix JIRA https://code.sec.samsung.net/jira/browse/GRE-2336.
Clear statis member when build examl.

Relative to patch https://github.com/Samsung/TizenFX/pull/3296.

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
looks good~

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Pull request merged**
