### PR TITLE
[XamlBuild] Fix issue of value node in XamlC

### PR DESCRIPTION
**Pull request by AdunFang**
Fix the issue of the sample below:

```
    <l:CustomButton x:FactoryMethod="CreateView" Size2D="850, 300">
        <x:Arguments>
            <x:String>Button create by factory method</x:String>
            <Color>Magenta</Color>
            <Position>
                100,600    <!--The value of position will not be set--!>
            </Position>
        </x:Arguments>
    </l:CustomButton>
```

### CODE REVIEW

**Review by zg2nets — APPROVED** [review]
looks good~

**Comment by xuelian-bai** [comment]
looks good to me

**Review by xiaowei-guan — APPROVED** [review]
LGTM

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by huayongxu — APPROVED** [review]
lgtm

**Review by AchoWang — APPROVED** [review]
Looks good to me

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by dongsug-song — APPROVED** [review]
looks good to me

**Pull request merged**
