### PR TITLE
[EXaml] Support Generate EXaml Tool

### PR DESCRIPTION
**Pull request by AdunFang**

### CODE REVIEW

**Comment by xuelian-bai** [comment]
looks good to me

**Review by zg2nets — APPROVED** [review]
lgtm

**Review by wb0716 — APPROVED** [review]
Good for me

**Review by zhouleonlei — APPROVED** [review]
LGTM

**Review by elishateng — APPROVED** [review]
LGTM

**Review by AchoWang — APPROVED** [review]
Looks good to me.

**Pull request merged**
